### ISSUE TITLE
Lightning Gallery - engineering review

### ISSUE THREAD

**Issue by manskx** [Lightning-Universe/JupyterLite_component#1]
Thanks for submitting your component to Lightning Gallary.

Here is some feedback regarding `LAI-JupyterLite-Component` in order to get accepted in the Lightning Gallery. 

1- Could you add more information about the component such as 
- Why to use the component?
- What's the value of JupyterLite vs Jupyterlap ?
- Documentation on how to use it ? if possible

2- Could you provide a `demo_app.py` that uses the component and show a case of why it's helpful with good explaining comments.

3- in the provided example, could you add some use cases and comments to help users to use your component easily ?

4- It's unclear what is the [contents](https://github.com/Lightning-AI/LAI-JupyterLite-Component/blob/main/lit_jupyterlite/component.py#L16), could you add some explanation and example usecases.

5- Could you add e2e test of the `demo_app.py` that starts the demo_app and checks that the notebook is starting successfully. It doesn't have to be could running test but simple as https://github.com/Lightning-AI/lightning/blob/2ea35182e054c0c55123e5df1f902f4bd600e892/tests/tests_app_examples/test_v0_app.py#L21

6- As a user, can I use the component in an advanced way? like having my own config file .... ? Is it possible to extend the component to support it?

7- Could you update the `setup.py` to include correct details about the component.

8- A running green CI is important to keep the component stable, could you check that?

If you have any questions, please reach out! we will be happy to assist you to land your component to the Lightning gallery.

cc: @zippeurfou

**Comment by zippeurfou** [comment]
@aniketmaurya fyi

**Comment by zippeurfou** [comment]
@aniketmaurya please put @manskx for review of your PR before closing it :)

**Comment by aniketmaurya** [comment]
Hi @manskx, I have tried to fix the issues in PR #2 and #3. I believe everything is fixed except for the CI test in Windows OS.

cc: @zippeurfou @naisofly

**Comment by manskx** [comment]
Thanks @aniketmaurya . Everything looks good 🚀 

I have a small [PR](https://github.com/Lightning-AI/LAI-JupyterLite-Component/pull/4) with minor suggestions, feel free to review it anytime so we can close this issue :)) 

FYI: @zippeurfou
